inherit_from:
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - 'Guardfile'
    - 'Rakefile'
    - 'bin/**/*'
    - 'config/**/*'
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.5

Rails:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
