inherit_from:
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.2

Rails:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
