sudo: false

addons:
  chrome: stable

notifications:
  email: false

rvm:
  - 2.4.3

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_install:
  - gem update --system
  - gem install bundler
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
