purl_url: 'https://purl.stanford.edu'
valid_purl_url: <%= /https?:\/\/purl\.stanford\.edu\/*/ %>
stacks_url: 'https://stacks.stanford.edu'
iiif_stacks_url: 'https://stacks.stanford.edu'
enable_media_viewer?: <%= false %>
embed_iframe_url: '//embed.stanford.edu/iframe'
squash_api_host: 'http://squash-host.example.com'
squash_api_key: 'abc123'
squash_disable: <%= (Rails.env.development? || Rails.env.test?) %>
geo_external_url: 'https://earthworks.stanford.edu/catalog/stanford-'
geo_wms_url: 'https://geowebservices.stanford.edu/geoserver/wms/'
was_thumbs_url: 'https://thumbnail-service-example'
streaming_url_suffixes:
  hls: 'playlist.m3u8'
  dash: 'manifest.mpd'
