purl_url: 'https://purl.stanford.edu'
# timeouts specified in seconds
purl_read_timeout: 2
purl_conn_timeout: 2
valid_purl_url: <%= /https?:\/\/purl\.stanford\.edu\/*/ %>
stacks_url: 'https://stacks.stanford.edu'
iiif_stacks_url: 'https://stacks.stanford.edu'
iiif_info_url: 'http://library.stanford.edu/projects/international-image-interoperability-framework'
enable_media_viewer?: <%= false %>
embed_iframe_url: '//embed.stanford.edu/iframe'
squash_api_host: 'http://squash-host.example.com'
squash_api_key: 'abc123'
squash_disable: <%= (Rails.env.development? || Rails.env.test?) %>
geo_external_url: 'https://earthworks.stanford.edu/catalog/stanford-'
geo_wms_url: 'https://geowebservices.stanford.edu/geoserver/wms/'
was_thumbs_url: 'https://thumbnail-service-example'
# timeouts specified in seconds
was_thumb_read_timeout: 5
was_thumb_conn_timeout: 5
streaming:
  source_types:
    - hls
  hls:
    suffix: '.m3u8'
    mimetype: 'application/x-mpegURL'
  dash:
    suffix: '.mpd'
    mimetype: 'application/dash+xml'
