purl_url: 'http://purl.stanford.edu'
stacks_url: 'http://stacks.stanford.edu'
iiif_stacks_url: 'https://stacks.stanford.edu'
embed_iframe_url: 'http://embed.stanford.edu/iframe'
squash_api_host: 'http://squash-host.example.com'
squash_api_key: 'abc123'
squash_disable: <%= (Rails.env.development? || Rails.env.test?) %>
