purl_url: 'https://purl.stanford.edu'
# timeouts specified in seconds
purl_read_timeout: 2
purl_conn_timeout: 2
valid_purl_url: <%= /https?:\/\/purl\.stanford\.edu\/*/ %>
stacks_url: 'https://stacks.stanford.edu'
iiif_stacks_url: 'https://stacks.stanford.edu'
iiif_info_url: 'http://library.stanford.edu/projects/international-image-interoperability-framework'
enable_media_viewer?: <%= false %>
embed_iframe_url: '//embed.stanford.edu/iframe'
jquery_version: '2.2.4'
geo_external_url: 'https://earthworks.stanford.edu/catalog/stanford-'
geo_wms_url: 'https://geowebservices.stanford.edu/geoserver/wms/'
was_thumbs_url: 'https://thumbnail-service-example'
# timeouts specified in seconds
was_thumb_read_timeout: 5
was_thumb_conn_timeout: 5
streaming:
  source_types:
    - hls
  hls:
    suffix: '.m3u8'
    mimetype: 'application/x-mpegURL'
  dash:
    suffix: '.mpd'
    mimetype: 'application/dash+xml'
stream:
  url: http://streaming-server.com:1935/stuff
  # streaming media file extensions we support
  video:
    - mov
    - mp4
    - mpeg
  audio:
    - mp3
